[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@openzeppelin/=lib/v4-core/lib/openzeppelin-contracts/",
  "@uniswap/v4-core/=lib/v4-core/"
]
fs_permissions = [{ access = "read-write", path = "./deployments" }]
solc_version = "0.8.24"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
