[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
remappings = [
  "@openzeppelin/=lib/v4-core/lib/openzeppelin-contracts/",
  "@uniswap/v4-core/=lib/v4-core/"
]
fs_permissions = [{ access = "read-write", path = "./deployments" }]
solc_version = "0.8.24"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
